# Site settings
title:          superagonist
description:    "blog"
#baseurl:        "/"
url:            "https://superagonist.github.io"
#url:            "http://localhost"

# Google Analytics
google_analytics: UA-145095049-1

# Author
author:
  name:         superagonist
  url:          https://superagonist.github.io
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Theme
remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
